### ISSUE TITLE
Extension enabling on non-LL files

### ISSUE THREAD

**Issue by EMJzero** [Qiu-Weidong/llvm-ir-language-support-for-vscode#1]
When having multiple file types opened on VS-Code, for some reason the extension operates as if it were always enabled, regardless of the filetype. The following screenshot shows the behaviour:

![temp](https://user-images.githubusercontent.com/38760911/229580611-f7ebd7fa-0e44-472a-a42b-592c96dfa0be.PNG)

The file opened on the right is configured to use the C highlighting, however the LLVM IR extension takes over for some reason...

**Comment by Qiu-Weidong** [comment]
Thanks for your issue. It has been fixed in version 0.5.4
